// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyGhiDanh.Data;

#nullable disable

namespace QuanLyGhiDanh.Migrations
{
    [DbContext(typeof(QuanLyGhiDanhContext))]
    [Migration("20230723074451_KetnoiSql")]
    partial class KetnoiSql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyGhiDanh.Data.Giangvien", b =>
                {
                    b.Property<int>("Idgiangvien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idgiangvien"));

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gioitinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hotengiangvien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Masothue")
                        .HasColumnType("float");

                    b.Property<string>("Mongiangday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ngaysinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sodienthoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idgiangvien");

                    b.ToTable("Giangvien");
                });

            modelBuilder.Entity("QuanLyGhiDanh.Data.Hocvien", b =>
                {
                    b.Property<int>("Idhocvien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idhocvien"));

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gioitinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hotenhocvien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ngaysinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenphuhuynh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idhocvien");

                    b.ToTable("Hocvien");
                });
#pragma warning restore 612, 618
        }
    }
}
